<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    
    <xs:element name="Mensaje">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Tipo" type="xs:string" />
                
                <xs:element name="Operacion" type="xs:string" minOccurs="0" />
                <xs:element name="Estado" type="xs:string" minOccurs="0" />
                
                <xs:element name="Datos" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:any processContents="skip" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

                <xs:element name="Control" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Codigo" type="xs:integer" />
                            <xs:element name="Detalle" type="xs:string" />
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
    
</xs:schema>